version = 0.1
[default.deploy.parameters]
stack_name = "ses-event-manager"
resolve_s3 = true
s3_prefix = "ses-event-manager"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BounceSNSTopic=\"arn:aws:sns:us-east-1:830321976775:ses-event\" STAGE=\"produccion\""
image_repositories = []
#on_failure = 'DELETE'
disable_rollback = true

[test.deploy.parameters]
stack_name = "ses-event-manager-test"
resolve_s3 = true
s3_prefix = "ses-event-manager-test"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BounceSNSTopic=\"arn:aws:sns:us-east-1:830321976775:ses-event\" STAGE=\"test\""
image_repositories = []
#on_failure = 'DELETE'
disable_rollback = true

[phoqo-produccion.deploy.parameters]
stack_name = "ses-event-manager"
resolve_s3 = true
s3_prefix = "ses-event-manager"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BounceSNSTopic=\"arn:aws:sns:us-east-1:654654368367:phoqo-notificaciones-topic\" PrincipalIdentity=\"phoqo.cl\" STAGE=\"produccion\" EventSource=\"phoqo.cl\" WebhookBus=\"phoqo-webhook\" PrivateBucket=\"phoqo-privatebucket-d5xdc2n8ky80\""
image_repositories = []
#on_failure = 'DELETE'
disable_rollback = true


[phoqo-pruebas.deploy.parameters]
stack_name = "ses-event-manager"
resolve_s3 = true
s3_prefix = "ses-event-manager"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BounceSNSTopic=\"arn:aws:sns:us-east-1:471112655224:phoqo-notificaciones-topic\" PrincipalIdentity=\"phoqo.cl\" STAGE=\"pruebas\" EventSource=\"phoqo.cl\" WebhookBus=\"phoqo-webhook\" PrivateBucket=\"phoqo-privatebucket-k7nbaqvoc1ja\""
image_repositories = []
#on_failure = 'DELETE'
disable_rollback = true
