AWSTemplateFormatVersion: 2010-09-09
Transform:
  - 'AWS::Serverless-2016-10-31'
Description: 'ses-dashboard-events'
Parameters:
  AWSEnv:
    Type: String
    Default: AWS
  STAGE:
    Type: String
    Default: ''
  BounceSNSTopic:
    Type: String
    Description: >-
      The bounce Amazon SNS Topic that has been created for the SES  identity. 
      Sepcify the SNS Topic by using its Amazon Resource Name (ARN).  Examples: 
      arn:aws:sns:us-east-1:830321976775:ses-event
Globals:
  Function:
    Runtime: nodejs18.x
    MemorySize: 256
    Timeout: 10
    Environment:
      Variables:
        TTL: '525600' #Minutos de TTL equivalente a un año
Resources:
  SESEmailSuppressionnTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ses-email-suppression
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      #        - AttributeName: timestamp
      #          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      #        - AttributeName: timestamp
      #          KeyType: RANGE
      BillingMode: PROVISIONED
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: 'expiration'
        Enabled: true
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0d7f8580-69ee-4297-a770-5cea5e7c801e
  SESEventsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ses-event
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      TimeToLiveSpecification:
        AttributeName: 'expiration'
        Enabled: true

      SSESpecification:
        SSEEnabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0d7f8580-69ee-4297-a770-5cea5e7c801e
  SESEmailTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ses-email
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      #        - AttributeName: timestamp
      #          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      #        - AttributeName: timestamp
      #          KeyType: RANGE
      BillingMode: PROVISIONED
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      SSESpecification:
        SSEEnabled: true

      TimeToLiveSpecification:
        AttributeName: 'expiration'
        Enabled: true
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0d7f8580-69ee-4297-a770-5cea5e7c801e

  SESSendEmailSQSDeadLeter:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 300
      QueueName: ses-send-email-dead.fifo
      FifoQueue: true
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1edfa9a2-4dfd-4ea6-a050-ae0884b7dcdb
  SESSendEmailSQS:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 300
      QueueName: ses-send-email.fifo
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SESSendEmailSQSDeadLeter.Arn
        maxReceiveCount: 4
      VisibilityTimeout: 30
    DependsOn:
      - SESSendEmailSQSDeadLeter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 00450781-3848-447b-85e7-526f54cb68f2

  SESEventSQSDeadLeter:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 300
      QueueName: ses-event-dead
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1edfa9a2-4dfd-4ea6-a050-ae0884b7dcdb

  SESEventSQS:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 300
      QueueName: ses-event
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SESEventSQSDeadLeter.Arn
        maxReceiveCount: 2
      VisibilityTimeout: 10
    DependsOn:
      - SESEventSQSDeadLeter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 00450781-3848-447b-85e7-526f54cb68f2
  SESEventSQSPolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref SESEventSQS
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Principal:
            Service: "sns.amazonaws.com"
          Action:
            - 'SQS:SendMessage'
            - 'SQS:ReceiveMessage'
          Effect: Allow
          Resource: !GetAtt SESEventSQS.Arn
          Condition:
            ArnEquals:
              'aws:SourceArn': !Ref BounceSNSTopic
    DependsOn:
      - SESEventSQS
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 321fa85f-b167-4be6-bdbf-ac675f03f754

  SESEventSQSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: sqs
      RawMessageDelivery: true
      Endpoint: !GetAtt SESEventSQS.Arn
      TopicArn: !Ref BounceSNSTopic
    DependsOn:
      - SESEventSQS
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7756bc4d-50de-4721-9457-5297a5bb3078

  ProcessSESQueue:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/node/
      Handler: SesNotification.handler
      FunctionName: ses-event-process
      Environment:
        Variables:
          TABLE_EVENT_NAME: !Ref SESEventsTable
          TABLE_EMAIL_NAME: !Ref SESEmailTable
          TABLE_EMAIL_SUPPRESSION_NAME: !Ref SESEmailSuppressionnTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEmailTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEventsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEmailSuppressionnTable
        - S3ReadPolicy:
            BucketName: '*'
        - EventBridgePutEventsPolicy:
            EventBusName: '*'
        - SQSSendMessagePolicy:
            QueueName: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
      Events:
        SESEventSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SESEventSQS.Arn
            BatchSize: 1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bce22d8f-5cbc-4935-aa75-d9b30ea96d3a
  ProcessSESQueueLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProcessSESQueue}'
      RetentionInDays: 7
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 29f463bb-b3e3-4cb1-b8b7-e2eb5bdd3a95
  ProcessSESSendQueue:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/python/src/
      Handler: ses_send_notification_sqs.handler
      Runtime: python3.8
      Timeout: 30
      FunctionName: ses-send-email-process
      Environment:
        Variables:
          TABLE_EVENT_NAME: !Ref SESEventsTable
          TABLE_EMAIL_NAME: !Ref SESEmailTable
          TABLE_EMAIL_SUPPRESSION_NAME: !Ref SESEmailSuppressionnTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEmailTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEventsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEmailSuppressionnTable
        - S3ReadPolicy:
            BucketName: '*'
        - SQSSendMessagePolicy:
            QueueName: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
      Events:
        SESEventSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SESSendEmailSQS.Arn
            BatchSize: 1
            ScalingConfig:
              MaximumConcurrency: 7
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bce22d8f-5cbc-4935-aa75-d9b30ea96d3a
  ProcessEmailSyncOS:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/python/src/
      Handler: sync_dynamo_os.handler
      Runtime: python3.8
      Timeout: 30
      FunctionName: ses-send-email-sync-os
      Environment:
        Variables:
          TABLE_EVENT_NAME: !Ref SESEventsTable
          TABLE_EMAIL_NAME: !Ref SESEmailTable
          TABLE_EMAIL_SUPPRESSION_NAME: !Ref SESEmailSuppressionnTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'es:*'
              Resource: '*'
      Events:
        DDBEvent:
          Type: DynamoDB
          Properties:
            Stream:
              !GetAtt SESEmailTable.StreamArn   # This must be the name of a DynamoDB table declared in the same template file
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
            Enabled: true
        DDBEventSupression:
          Type: DynamoDB
          Properties:
            Stream:
              !GetAtt SESEmailSuppressionnTable.StreamArn   # This must be the name of a DynamoDB table declared in the same template file
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
            Enabled: true
        DDBEventEvents:
          Type: DynamoDB
          Properties:
            Stream:
              !GetAtt   SESEventsTable.StreamArn   # This must be the name of a DynamoDB table declared in the same template file
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
            Enabled: true
#  EmailEventSync:
#    Type: AWS::Lambda::EventSourceMapping
#    Properties:
#      EventSourceArn: !GetAtt SESEventsTable.StreamArn
#      FunctionName: !GetAtt ProcessEmailSyncOS.Arn
  ProcessSESSendQueueLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProcessSESSendQueue}'
      RetentionInDays: 7
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 29f463bb-b3e3-4cb1-b8b7-e2eb5bdd3a95
  SendNotificationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/node/
      Handler: SendNotification.handler
      FunctionName: ses-send-email
      Environment:
        Variables:
          TABLE_EVENT_NAME: !Ref SESEventsTable
          TABLE_EMAIL_NAME: !Ref SESEmailTable
          TABLE_EMAIL_SUPPRESSION_NAME: !Ref SESEmailSuppressionnTable
          SQS_URL: !Ref SESSendEmailSQS
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEmailTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEmailSuppressionnTable
        - S3ReadPolicy:
            BucketName: '*'
        - SQSSendMessagePolicy:
            QueueName: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c97126fc-566e-4d2e-bec6-a4275cd5e294
  SendNotificationFunctionLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${SendNotificationFunction}'
      RetentionInDays: 7
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 29f463bb-b3e3-4cb1-b8b7-e2eb5bdd3a95

Metadata:
  'AWS::CloudFormation::Designer':
    968b2a2a-7489-4b00-8cf4-8c7b2bf967a5:
      size:
        width: 150
        height: 150
      position:
        x: 20
        'y': 100
      z: 1
      embeds:
        - c97126fc-566e-4d2e-bec6-a4275cd5e294
    29f463bb-b3e3-4cb1-b8b7-e2eb5bdd3a95:
      size:
        width: 150
        height: 150
      position:
        x: 470
        'y': 110
      z: 1
      embeds:
        - bce22d8f-5cbc-4935-aa75-d9b30ea96d3a
    0d7f8580-69ee-4297-a770-5cea5e7c801e:
      size:
        width: 60
        height: 60
      position:
        x: 310
        'y': 160
      z: 1
      embeds: [ ]
    c97126fc-566e-4d2e-bec6-a4275cd5e294:
      size:
        width: 60
        height: 60
      position:
        x: 80
        'y': 160
      z: 2
      pareker nt: 968b2a2a-7489-4b00-8cf4-8c7b2bf967a5
      embeds: [ ]
    1edfa9a2-4dfd-4ea6-a050-ae0884b7dcdb:
      size:
        width: 60
        height: 60
      position:
        x: 360
        'y': 390
      z: 1
      embeds: [ ]
    00450781-3848-447b-85e7-526f54cb68f2:
      size:
        width: 60
        height: 60
      position:
        x: 510
        'y': 390
      z: 1
      embeds: [ ]
    bce22d8f-5cbc-4935-aa75-d9b30ea96d3a:
      size:
        width: 60
        height: 60
      position:
        x: 510
        'y': 160
      z: 2
      parent: 29f463bb-b3e3-4cb1-b8b7-e2eb5bdd3a95
      embeds: [ ]
    7756bc4d-50de-4721-9457-5297a5bb3078:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 440
      z: 1
      embeds: [ ]
    321fa85f-b167-4be6-bdbf-ac675f03f754:
      size:
        width: 60
        height: 60
      position:
        x: 710
        'y': 390
      z: 1
      embeds: [ ]
      dependson:
        - 00450781-3848-447b-85e7-526f54cb68f2
