AWSTemplateFormatVersion: 2010-09-09
Description: 'ses-dashboard-events'
Transform:
  - 'AWS::Serverless-2016-10-31'
Parameters:
  BounceSNSTopic:
    Type: String
    Description: >-
      The bounce Amazon SNS Topic that has been created for the SES  identity. 
      Sepcify the SNS Topic by using its Amazon Resource Name (ARN).  Examples: 
      arn:aws:sns:us-east-1:830321976775:ses-event
Globals:
  Function:
    Runtime: nodejs18.x
    MemorySize: 128
    Timeout: 10
Resources:
  SESEventsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ses-event
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0d7f8580-69ee-4297-a770-5cea5e7c801e
  SESEmailTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ses-email
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 0d7f8580-69ee-4297-a770-5cea5e7c801e

  SESSendEmailSQSDeadLeter:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 300
      QueueName: ses-send-email-dead.fifo
      FifoQueue: true
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1edfa9a2-4dfd-4ea6-a050-ae0884b7dcdb
  SESSendEmailSQS:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 300
      QueueName: ses-send-email.fifo
      FifoQueue: true
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SESSendEmailSQSDeadLeter.Arn
        maxReceiveCount: 4
      VisibilityTimeout: 10
    DependsOn:
      - SESSendEmailSQSDeadLeter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 00450781-3848-447b-85e7-526f54cb68f2

  SESEventSQSDeadLeter:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 300
      QueueName: ses-event-dead
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 1edfa9a2-4dfd-4ea6-a050-ae0884b7dcdb
  SESEventSQS:
    Type: 'AWS::SQS::Queue'
    Properties:
      MessageRetentionPeriod: 300
      QueueName: ses-event
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SESEventSQSDeadLeter.Arn
        maxReceiveCount: 2
      VisibilityTimeout: 10
    DependsOn:
      - SESEventSQSDeadLeter
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 00450781-3848-447b-85e7-526f54cb68f2
  SESEventSQSPolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      Queues:
        - !Ref SESEventSQS
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Principal:
            Service: "sns.amazonaws.com"
          Action:
            - 'SQS:SendMessage'
            - 'SQS:ReceiveMessage'
          Effect: Allow
          Resource: !GetAtt SESEventSQS.Arn
          Condition:
            ArnEquals:
              'aws:SourceArn': !Ref BounceSNSTopic
    DependsOn:
      - SESEventSQS
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 321fa85f-b167-4be6-bdbf-ac675f03f754
  SESEventSQSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Protocol: sqs
      RawMessageDelivery: true
      Endpoint: !GetAtt SESEventSQS.Arn
      TopicArn: !Ref BounceSNSTopic
    DependsOn:
      - SESEventSQS
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 7756bc4d-50de-4721-9457-5297a5bb3078

  ProcessSESQueue:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/ses_queue_handler/
      Handler: SesNotification.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SESEventsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEventsTable
      Events:
        SESEventSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SESEventSQS.Arn
            BatchSize: 1
            ScalingConfig:
              MaximumConcurrency: 5
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bce22d8f-5cbc-4935-aa75-d9b30ea96d3a
  SendNotificationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/ses_queue_send_handler/
      Handler: SendNotification.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SESEmailTable
          SQS_URL: !Ref SESSendEmailSQS
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEmailTable
        - S3ReadPolicy:
            BucketName: '*'
        - SQSSendMessagePolicy:
            QueueName: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: '*'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c97126fc-566e-4d2e-bec6-a4275cd5e294
  GetEventsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/get_events/
      Handler: GetEvents.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref SESEventsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SESEventsTable
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c97126fc-566e-4d2e-bec6-a4275cd5e294
  GetEventsFunctionLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${GetEventsFunction}'
      RetentionInDays: 14
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 968b2a2a-7489-4b00-8cf4-8c7b2bf967a5
  ProcessSESQueueLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProcessSESQueue}'
      RetentionInDays: 7
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 29f463bb-b3e3-4cb1-b8b7-e2eb5bdd3a95

Metadata:
  'AWS::CloudFormation::Designer':
    968b2a2a-7489-4b00-8cf4-8c7b2bf967a5:
      size:
        width: 150
        height: 150
      position:
        x: 20
        'y': 100
      z: 1
      embeds:
        - c97126fc-566e-4d2e-bec6-a4275cd5e294
    29f463bb-b3e3-4cb1-b8b7-e2eb5bdd3a95:
      size:
        width: 150
        height: 150
      position:
        x: 470
        'y': 110
      z: 1
      embeds:
        - bce22d8f-5cbc-4935-aa75-d9b30ea96d3a
    0d7f8580-69ee-4297-a770-5cea5e7c801e:
      size:
        width: 60
        height: 60
      position:
        x: 310
        'y': 160
      z: 1
      embeds: [ ]
    c97126fc-566e-4d2e-bec6-a4275cd5e294:
      size:
        width: 60
        height: 60
      position:
        x: 80
        'y': 160
      z: 2
      pareker nt: 968b2a2a-7489-4b00-8cf4-8c7b2bf967a5
      embeds: [ ]
    1edfa9a2-4dfd-4ea6-a050-ae0884b7dcdb:
      size:
        width: 60
        height: 60
      position:
        x: 360
        'y': 390
      z: 1
      embeds: [ ]
    00450781-3848-447b-85e7-526f54cb68f2:
      size:
        width: 60
        height: 60
      position:
        x: 510
        'y': 390
      z: 1
      embeds: [ ]
    bce22d8f-5cbc-4935-aa75-d9b30ea96d3a:
      size:
        width: 60
        height: 60
      position:
        x: 510
        'y': 160
      z: 2
      parent: 29f463bb-b3e3-4cb1-b8b7-e2eb5bdd3a95
      embeds: [ ]
    7756bc4d-50de-4721-9457-5297a5bb3078:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 440
      z: 1
      embeds: [ ]
    321fa85f-b167-4be6-bdbf-ac675f03f754:
      size:
        width: 60
        height: 60
      position:
        x: 710
        'y': 390
      z: 1
      embeds: [ ]
      dependson:
        - 00450781-3848-447b-85e7-526f54cb68f2
